import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import registrationsRouter from "./registrations";
import newsRouter from "./news";
import contestantsRouter from "./contestants";
import sponsorsRouter from "./sponsors";
import exhibitionsRouter from "./exhibitions";
import adminRouter from "./admin";
import socialMarketingRouter from "./social-marketing";
import storageRouter from "./storage";
import paymentsRouter from "./payments";
import checkinRouter from "./checkin";
import emailTemplatesRouter from "./email-templates";
import adminUsersRouter from "./admin-users";
import promoCodesRouter from "./promo-codes";
import refundRequestsRouter from "./refund-requests";
import contestantVotesRouter from "./contestant-votes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(registrationsRouter);
router.use(newsRouter);
router.use(contestantsRouter);
router.use(sponsorsRouter);
router.use(exhibitionsRouter);
router.use(adminRouter);
router.use(socialMarketingRouter);
router.use(storageRouter);
router.use(paymentsRouter);
router.use(checkinRouter);
router.use(emailTemplatesRouter);
router.use(adminUsersRouter);
router.use(promoCodesRouter);
router.use(refundRequestsRouter);
router.use(contestantVotesRouter);

export default router;
